#!/usr/bin/env python3
"""Build the lexicon load files from the downloaded datasets.

    python3 scripts/lexicon/build.py <extract-dir> <out-dir>

<extract-dir> holds the unzipped downloads (see README.md for the layout):
    ds/     sqlite-data-langauges-*.zip
    talks/  6TALKS-*.zip
    pc/     parse-conjugator-*.zip (inner zip unpacked)

Writes one tab-separated file per lex.* table (PostgreSQL COPY text
format) into <out-dir>, plus sources.tsv and report.json. Nothing is
dropped for licence reasons here: every row is tagged with its source and
lex.sources.visibility decides who sees it (SOURCES below).
"""
import csv
import json
import re
import sqlite3
import sys
import unicodedata
from pathlib import Path

csv.field_size_limit(10_000_000)

# code: (name, url, licence, licence_url, visibility, origin, notes)
SOURCES = {
    'cc_cedict': ('CC-CEDICT', 'https://cc-cedict.org/wiki/', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', 'public',
                  'parse-conjugator/19ctalks/ctalk.db (cedict)', 'Chinese-English dictionary; POS/HSK/radical columns were added by the C-Talk app.'),
    'hsk_lists': ('HSK word lists 1-6', '', 'Public word lists', '', 'public', 'sqlite-data-langauges/data-chinese/hsk', 'Level tags + short glosses.'),
    'makemeahanzi': ('Make Me a Hanzi', 'https://github.com/skishore/makemeahanzi', 'LGPL / Arphic Public License', 'https://github.com/skishore/makemeahanzi#license', 'public',
                     'sqlite-data-langauges/data-chinese/makemeahanzi.txt', 'Character decomposition and etymology.'),
    'cangjie5': ('Cangjie 5 code table', 'http://www.chinesecj.com', 'Unclear', '', 'review', 'sqlite-data-langauges/data-chinese/cangjie5.txt', 'Input-method codes from chinesecj.com.'),
    'jmdict': ('JMdict / EDICT', 'https://www.edrdg.org/jmdict/j_jmdict.html', 'CC BY-SA 4.0 (EDRDG)', 'https://www.edrdg.org/edrdg/licence.html', 'public',
               'sqlite-data-langauges/data-japanese/dictionary.db (words, rank 99999)', 'Japanese-English dictionary.'),
    'jtalk_core': ('J-Talk ranked core words', 'https://j-talk.com', 'Unclear', '', 'review', 'data-japanese/dictionary.db (words, rank < 99999)',
                   'Hand-ranked particles/core words with J-Talk style glosses ("^t ..."); origin unclear.'),
    'kanjikana': ('kanjikana.com kanji catalog', 'https://kanjikana.com', 'Scraped — copyrighted', '', 'admin_only',
                  'data-japanese/dictionary.db (kanji_catalog) + kanjikana/', 'Scraped by jtalk/scripts/discover_pages.py.'),
    'wikdict': ('WikDict', 'https://www.wikdict.com', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', 'public',
                'data-european/sources/*-en.sqlite3 + dictionary.sqlite', 'Built from Wiktionary.'),
    'kaikki': ('Kaikki (Wiktextract)', 'https://kaikki.org', 'CC BY-SA 4.0 / GFDL', 'https://kaikki.org/dictionary/rawdata.html', 'public',
               'data-european/dictionary.sqlite (kaikki*)', 'Latin and Greek lemmas and forms from Wiktionary.'),
    'ipa_dict': ('ipa-dict', 'https://github.com/open-dict-data/ipa-dict', 'MIT', 'https://github.com/open-dict-data/ipa-dict/blob/master/LICENSE', 'public',
                 'data-european/sources/{de,es_ES,fr_FR,fr_QC}.txt', 'IPA pronunciations.'),
    'hunspell': ('Hunspell dictionaries (de/es/fr)', '', 'GPL / LGPL / MPL (per dictionary)', '', 'review',
                 'data-european/sources/*_dic.txt', 'Spell-check word lists with affix flags.'),
    'massivedict': ('"MassiveDict" rows', '', 'Unknown origin', '', 'admin_only', 'data-european/dictionary.sqlite',
                    '~634k rows of unknown origin with many junk glosses.'),
    'ltalk_morph': ('L-Talk generated forms', '', 'Generated by the L-Talk app', '', 'review', 'data-european/dictionary.sqlite (MorphologyEngine)',
                    'Inflected forms produced by rules; quality unchecked.'),
    'ltalk_misc': ('L-Talk misc rows', '', 'Unknown', '', 'review', 'data-european/dictionary.sqlite (no source tag)', ''),
    'openrussian': ('OpenRussian', 'https://en.openrussian.org', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', 'public',
                    'data-russian/openrussian/*.csv', 'Russian words, declensions, conjugations; English + German glosses.'),
    'rtalk_dict': ('R-Talk offline dictionary', '', 'Unknown (built by the R-Talk app)', '', 'review', 'data-russian/rtalk.db (offline_dictionary)', ''),
    'zaliznyak_stress': ('Russian stress list (Zaliznyak-based)', '', 'Unclear', '', 'review', 'data-russian/rtalk.db (stress_dict)',
                         'Stressed-vowel index per word form.'),
    'arabeyes': ('Arabeyes Arabic-English wordlist', 'https://www.arabeyes.org', 'GPL', 'https://www.gnu.org/licenses/gpl-3.0.html', 'public',
                 'data-arabic/arabeyes.sqlite + atalk_full_vocabulary.sqlite', 'Mostly unvocalized.'),
    'atalk_curated': ('A-Talk curated words', '', 'Own data (written for the A-Talk app)', '', 'public', 'data-arabic/atalk_full_vocabulary.sqlite (curated)', ''),
    'hanswehr': ('Hans Wehr dictionary', '', 'Copyrighted', '', 'admin_only', 'data-arabic/hanswehr.sqlite + atalk_full_vocabulary.sqlite', ''),
    'quran_roots': ('Quran word → root list', '', 'Unclear', '', 'review', 'data-arabic/hanswehr.sqlite (QURAN)', ''),
    'atalk_cache': ('A-Talk analysis cache', '', 'Generated', '', 'review', 'data-arabic/vocab_cache.sqlite', ''),
    'cooljugator': ('Cooljugator', 'https://cooljugator.com', 'Scraped — used by owner decision', '', 'public',
                    'all-conjugation-data/conjugator.db', 'Verb tables, translations, example sentences, related verbs (scraped). '
                    'Owner decided (2026-10-03) to use it publicly; can be switched off here at any time.'),
    'polyglot_registry': ('Polyglot registry (19parse)', '', 'Machine translation, unknown API', '', 'review',
                          'translations-data/database.sqlite', 'Words in 16 languages and auto-generated translation bonds.'),
    'polyglot_chars': ('Polyglot character dictionary (19parse)', '', 'Unknown', '', 'review',
                       'translations-data/database.sqlite (character_dictionary)', ''),
    'easymandarin': ('easymandarin.news articles + audio', 'https://easymandarin.news', 'Copyrighted', '', 'admin_only',
                     'parse-conjugator/19ctalks/ctalk.db (articles)', 'News articles and mp3 links.'),
    'ctalk_multilingual': ('C-Talk multilingual concepts', '', 'Generated by the C-Talk app', '', 'review', '19ctalks/ctalk.db (multilingual_*)', ''),
    'demo_texts': ('Clone apps\' saved demo texts', '', 'Mixed', '', 'review', 'conversions/shares/saved_texts tables', 'Sample texts saved in the clone apps.'),
}

LANG_MAP = {'gr': 'el', 'ee': 'et', 'hw': 'haw', 'run': 'ru', 'rua': 'ru', 'fin': 'fi', 'fia': 'fi'}
CONJ_POS = {'run': 'noun', 'rua': 'adjective', 'fin': 'noun', 'fia': 'adjective'}
ARABIC_MARKS = re.compile('[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed\u0640]')


def norm(lang, s):
    s = (s or '').strip()
    if lang == 'ar':
        s = ARABIC_MARKS.sub('', s).replace('أ', 'ا').replace('إ', 'ا').replace('آ', 'ا')
        return s
    if lang in ('zh', 'ja'):
        return s
    s = s.replace("'", '').replace('\u0301', '').lower()
    s = ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')
    return unicodedata.normalize('NFC', s)


def esc(v):
    if v is None:
        return r'\N'
    if isinstance(v, (dict, list)):
        v = json.dumps(v, ensure_ascii=False)
    v = str(v)
    return v.replace('\\', '\\\\').replace('\t', '\\t').replace('\n', '\\n').replace('\r', '\\r')


class Table:
    def __init__(self, out, name):
        self.f = open(out / f'{name}.tsv', 'w', encoding='utf-8')
        self.n = 0

    def add(self, *cols):
        self.n += 1
        self.f.write('\t'.join(esc(c) for c in cols) + '\n')
        return self.n

    def close(self):
        self.f.close()


class Builder:
    def __init__(self, root, out):
        self.root = root
        self.out = out
        out.mkdir(parents=True, exist_ok=True)
        self.src = {code: i + 1 for i, code in enumerate(SOURCES)}
        self.entries = {}       # (lang, headword, reading, pos) -> [id, freq, level, extra]
        self.by_hw = {}         # (lang, headword) -> first id
        self.by_hw_read = {}    # (lang, headword, reading) -> first id
        self.by_id = {}         # id -> the mutable entry list
        self.pivot = set()
        self.sense_seen = set()
        self.t = {n: Table(out, n) for n in ('entry_sources', 'senses', 'forms', 'prons', 'conj_forms', 'links', 'chars', 'sentences', 'texts', 'media')}
        self.counts = {code: 0 for code in SOURCES}

    # ── helpers ────────────────────────────────────────────────
    def db(self, rel):
        p = self.root / rel
        if not p.exists():
            print(f'  skip (missing): {rel}')
            return None
        return sqlite3.connect(f'file:{p}?mode=ro&immutable=1', uri=True)

    def entry(self, src, lang, headword, reading='', pos='', freq=None, level=None, extra=None, ext_id=None):
        headword = str(headword or '').strip()
        if not headword:
            return None
        reading = str(reading or '').strip()
        pos = str(pos or '').strip().lower()
        key = (lang, headword, reading, pos)
        e = self.entries.get(key)
        if e is None:
            e = [len(self.entries) + 1, freq, level, dict(extra) if extra else None]
            self.entries[key] = e
            self.by_id[e[0]] = e
            self.by_hw.setdefault((lang, headword), e[0])
            self.by_hw_read.setdefault((lang, headword, reading), e[0])
        else:
            if freq is not None and (e[1] is None or freq < e[1]):
                e[1] = freq
            if level and not e[2]:
                e[2] = level
            if extra:
                e[3] = {**extra, **(e[3] or {})}
        sid = self.src[src]
        if (e[0], sid) not in self.pivot:
            self.pivot.add((e[0], sid))
            self.t['entry_sources'].add(e[0], sid, ext_id)
            self.counts[src] += 1
        return e[0]

    def find(self, lang, headword, reading=None):
        if reading is not None:
            hit = self.by_hw_read.get((lang, headword, reading))
            if hit:
                return hit
        return self.by_hw.get((lang, headword))

    def sense(self, src, entry_id, gloss, lang='en', no=1, definition=None):
        gloss = str(gloss or '').strip()
        if not entry_id or not gloss:
            return
        key = (entry_id, self.src[src], lang, gloss)
        if key in self.sense_seen:
            return
        self.sense_seen.add(key)
        self.t['senses'].add(len(self.sense_seen), entry_id, self.src[src], lang, no, gloss, definition or None)
        self.counts[src] += 1

    def form(self, src, lang, form, entry_id=None, lemma=None, tags=''):
        form = str(form or '').strip()
        if not form:
            return
        self.t['forms'].add(self.t['forms'].n + 1, lang, form, norm(lang, form), entry_id, lemma, tags or '', self.src[src])
        self.counts[src] += 1

    def pron(self, src, lang, word, ipa=None, stress=None, variant=''):
        if not word or (not ipa and stress is None):
            return
        self.t['prons'].add(self.t['prons'].n + 1, lang, word, norm(lang, word), ipa, stress, variant, self.src[src])
        self.counts[src] += 1

    # ── Chinese ────────────────────────────────────────────────
    def chinese(self):
        print('Chinese')
        c = self.db('pc/19ctalks/ctalk.db')
        if c:
            for trad, simp, pnum, ptone, gloss, bopo, pos, hsk, rad, dec in c.execute(
                    'SELECT trad, simp, pinyin_num, pinyin_tone, gloss, bopomofo, pos, hsk, radical, decomposition FROM cedict'):
                extra = {k: v for k, v in (('trad', trad), ('pinyin_num', pnum), ('bopomofo', bopo), ('radical', rad), ('decomposition', dec)) if v and v != '？'}
                eid = self.entry('cc_cedict', 'zh', simp, ptone, pos, level=f'HSK{hsk}' if hsk else None, extra=extra)
                self.sense('cc_cedict', eid, gloss)
                if trad and trad != simp:
                    self.form('cc_cedict', 'zh', trad, eid, simp, 'traditional')
        for n in range(1, 7):
            p = self.root / f'ds/data-chinese/hsk/hsk{n}.csv'
            if not p.exists():
                continue
            for row in csv.reader(p.open(encoding='utf-8')):
                if len(row) < 3:
                    continue
                word, py, gloss = row[0].strip(), row[1].strip(), ','.join(row[2:]).strip()
                eid = self.find('zh', word, py)
                if eid:
                    self.entry_existing_pivot(eid, 'hsk_lists')
                    e = self.by_id[eid]
                    if not e[2]:
                        e[2] = f'HSK{n}'
                else:
                    eid = self.entry('hsk_lists', 'zh', word, py, '', level=f'HSK{n}')
                self.sense('hsk_lists', eid, gloss)
        p = self.root / 'ds/data-chinese/makemeahanzi.txt'
        if p.exists():
            for line in p.open(encoding='utf-8'):
                d = json.loads(line)
                self.t['chars'].add(self.t['chars'].n + 1, d['character'], 'Hani', {'pinyin': d.get('pinyin') or []}, d.get('definition'),
                                    d.get('radical'), None, d.get('decomposition'), None, {'etymology': d['etymology']} if d.get('etymology') else None,
                                    self.src['makemeahanzi'])
                self.counts['makemeahanzi'] += 1
        p = self.root / 'ds/data-chinese/cangjie5.txt'
        if p.exists():
            for line in p.open(encoding='utf-8'):
                parts = line.rstrip('\n').split('\t')
                if len(parts) < 2 or line.startswith('#') or not parts[0] or len(parts[0]) > 2:
                    continue
                ch, code = (parts[0], parts[1]) if not parts[0].isascii() else (parts[1], parts[0])
                if ch.isascii():
                    continue
                self.t['chars'].add(self.t['chars'].n + 1, ch, 'Hani', {'cangjie': code}, None, None, None, None, None, None, self.src['cangjie5'])
                self.counts['cangjie5'] += 1

    # ── Japanese ───────────────────────────────────────────────
    def japanese(self):
        print('Japanese')
        c = self.db('ds/data-japanese/dictionary.db')
        if not c:
            return
        for word, reading, gloss, pos, rank in c.execute('SELECT word, reading, gloss, pos, rank FROM words'):
            src = 'jmdict' if (rank or 99999) >= 99999 else 'jtalk_core'
            eid = self.entry(src, 'ja', word, reading, pos, freq=None if src == 'jmdict' else rank)
            self.sense(src, eid, gloss)
        for row in c.execute('SELECT character, meaning, jlpt, kanken, joyo_grade, is_joyo, themes, radicals, stroke_count, on_readings, kun_readings, meanings_full, frequency FROM kanji_catalog'):
            ch, meaning, jlpt, kanken, grade, joyo, themes, rads, strokes, on, kun, full, freq = row
            self.t['chars'].add(self.t['chars'].n + 1, ch, 'Jpan', {'on': on, 'kun': kun}, meaning, rads, strokes, None,
                                {k: v for k, v in (('jlpt', jlpt), ('kanken', kanken), ('joyo_grade', grade), ('is_joyo', joyo)) if v not in (None, '')},
                                {k: v for k, v in (('themes', themes), ('meanings_full', full), ('frequency', freq)) if v not in (None, '')},
                                self.src['kanjikana'])
            self.counts['kanjikana'] += 1

    # ── European (de/es/fr/la/el) ──────────────────────────────
    def european(self):
        print('European')
        c = self.db('ds/data-european/dictionary.sqlite')
        if c:
            for lang, word, lemma, pos, ipa, reading, gloss, details in c.execute('SELECT lang, word, lemma, pos, ipa, reading, gloss, details FROM words'):
                try:
                    d = json.loads(details) if details else {}
                except ValueError:
                    d = {}
                if not isinstance(d, dict):
                    d = {'raw': d}
                s = d.get('source') or ''
                if s.startswith('kaikki') and s.endswith('_form'):
                    eid = self.find(lang, d.get('lemma') or lemma)
                    self.form('kaikki', lang, word, eid, d.get('lemma') or lemma, ','.join(d.get('tags') or []))
                    self.pron('kaikki', lang, word, ipa or None)
                    continue
                if s == 'MorphologyEngine':
                    self.form('ltalk_morph', lang, word, self.find(lang, lemma), lemma, d.get('form') or '')
                    self.pron('ltalk_morph', lang, word, ipa or None)
                    continue
                src = {'WikDict': 'wikdict', 'MassiveDict': 'massivedict'}.get(s) or ('kaikki' if s.startswith('kaikki') else 'ltalk_misc')
                eid = self.entry(src, lang, word, '', pos or d.get('pos') or '')
                self.sense(src, eid, gloss)
                self.pron(src, lang, word, ipa or None)
            for slug, lang, title, content, opt, created in c.execute('SELECT slug, lang, title, content, convert_option, created_at FROM saved_texts'):
                self.t['texts'].add(self.t['texts'].n + 1, lang, title or slug, content or '', None, {'app': 'L-Talk'}, self.src['demo_texts'])
                self.counts['demo_texts'] += 1
        for lang in ('de', 'es', 'fr'):
            w = self.db(f'ds/data-european/sources/{lang}-en.sqlite3')
            if not w:
                continue
            for lexentry, sense_num, sense, rep, trans, score, good, imp in w.execute(
                    'SELECT lexentry, sense_num, sense, written_rep, trans_list, score, is_good, importance FROM translation'):
                pos = ''
                if lexentry and '__' in lexentry:
                    pos = lexentry.split('__')[1]
                eid = self.entry('wikdict', lang, rep, '', pos)
                gloss = ', '.join(t.strip() for t in (trans or '').split('|') if t.strip())
                self.sense('wikdict', eid, gloss, no=int(sense_num) if str(sense_num or '').isdigit() else 1, definition=sense)
        for fname, lang, variant in (('de.txt', 'de', ''), ('es_ES.txt', 'es', 'ES'), ('fr_FR.txt', 'fr', 'FR'), ('fr_QC.txt', 'fr', 'QC')):
            p = self.root / 'ds/data-european/sources' / fname
            if not p.exists():
                continue
            for line in p.open(encoding='utf-8'):
                if '\t' not in line:
                    continue
                word, ipas = line.rstrip('\n').split('\t', 1)
                for ipa in ipas.split(', '):
                    self.pron('ipa_dict', lang, word, ipa.strip(), variant=variant)
        for lang in ('de', 'es', 'fr'):
            p = self.root / f'ds/data-european/sources/{lang}_dic.txt'
            if not p.exists():
                continue
            for i, line in enumerate(p.open(encoding='utf-8', errors='replace')):
                line = line.rstrip('\n')
                if i == 0 or not line or line.startswith(('\t', '#')):
                    continue
                word, _, flags = line.partition('/')
                self.form('hunspell', lang, word, None, None, 'hunspell:' + flags if flags else 'hunspell')

    # ── Russian ────────────────────────────────────────────────
    def russian(self):
        print('Russian')
        base = self.root / 'ds/data-russian/openrussian'
        posmap = {'nouns': 'noun', 'adjectives': 'adjective', 'verbs': 'verb', 'others': ''}
        for fname, pos in posmap.items():
            p = base / f'{fname}.csv'
            if not p.exists():
                continue
            for row in csv.DictReader(p.open(encoding='utf-8'), delimiter='\t'):
                bare = row.get('bare') or ''
                extra = {k: row[k] for k in ('gender', 'aspect', 'partner', 'animate', 'type') if row.get(k)}
                eid = self.entry('openrussian', 'ru', bare, row.get('accented') or '', pos or (row.get('type') or ''), extra=extra)
                for gl, col in (('en', 'translations_en'), ('de', 'translations_de')):
                    self.sense('openrussian', eid, row.get(col), lang=gl)
                forms = {k: v for k, v in row.items() if k not in ('bare', 'accented', 'translations_en', 'translations_de', 'gender', 'partner',
                                                                     'animate', 'indeclinable', 'sg_only', 'pl_only', 'aspect', 'type')
                         and k is not None and isinstance(v, str) and v}
                if pos == 'verb':
                    for i, (k, v) in enumerate(forms.items()):
                        self.t['conj_forms'].add(self.t['conj_forms'].n + 1, eid, self.src['openrussian'], 'OpenRussian', k.rsplit('_', 1)[0], k, v, None, None, i)
                        self.counts['openrussian'] += 1
                else:
                    for k, v in forms.items():
                        for f in v.split(','):
                            self.form('openrussian', 'ru', f.strip(), eid, bare, k)
        c = self.db('ds/data-russian/rtalk.db')
        if c:
            for word, lemma, pos, short, detail in c.execute('SELECT word, lemma, pos, short_gloss, detailed_def FROM offline_dictionary'):
                if word == lemma:
                    eid = self.entry('rtalk_dict', 'ru', lemma, '', pos)
                    self.sense('rtalk_dict', eid, short, definition=detail)
                else:
                    self.form('rtalk_dict', 'ru', word, self.find('ru', lemma), lemma, pos or '')
            for word, idx in c.execute('SELECT word, vowel_idx FROM stress_dict'):
                self.pron('zaliznyak_stress', 'ru', word, None, idx)
            for _id, title, text, opt, data, created in c.execute('SELECT id, title, original_text, convert_option, data_json, created_at FROM conversions'):
                self.t['texts'].add(self.t['texts'].n + 1, 'ru', title or '', text or '', None, {'app': 'R-Talk'}, self.src['demo_texts'])
                self.counts['demo_texts'] += 1

    # ── Arabic ─────────────────────────────────────────────────
    def arabic(self):
        print('Arabic')
        c = self.db('ds/data-arabic/atalk_full_vocabulary.sqlite')
        if c:
            for ar, voc, root, lemma, pos, tr, gloss, definition, source, freq in c.execute(
                    'SELECT arabic, vocalized, root, lemma, pos, transliteration, gloss, definition, source, frequency FROM vocabulary'):
                src = {'arabeyes': 'arabeyes', 'curated': 'atalk_curated', 'hanswehr': 'hanswehr'}.get(source, 'arabeyes')
                extra = {k: v for k, v in (('vocalized', voc), ('root', root), ('lemma', lemma)) if v and v != ar}
                eid = self.entry(src, 'ar', ar, tr or '', pos, freq=freq or None, extra=extra)
                self.sense(src, eid, gloss, definition=definition)
        a = self.db('ds/data-arabic/arabeyes.sqlite')
        if a:
            for ar, en in a.execute('SELECT ar, en FROM dict'):
                eid = self.find('ar', (ar or '').strip()) or self.entry('arabeyes', 'ar', ar)
                if eid:
                    self.entry_existing_pivot(eid, 'arabeyes')
                self.sense('arabeyes', eid, en)
        h = self.db('ds/data-arabic/hanswehr.sqlite')
        if h:
            translit = dict(h.execute('SELECT id, transliteration FROM TRANSLITERATION'))
            for _id, word, definition, is_root, parent in h.execute('SELECT id, word, definition, is_root, parent_id FROM DICTIONARY'):
                eid = self.entry('hanswehr', 'ar', word, translit.get(_id) or '', 'root' if is_root else '', ext_id=str(_id),
                                 extra={'parent_id': parent} if parent else None)
                self.sense('hanswehr', eid, (definition or '')[:300], definition=definition)
            for surah, ayah, word, root in h.execute('SELECT SURAH, AYAH, WORD, ROOT_WORD FROM QURAN'):
                # WORD is the word's position in the ayah, not its text.
                self.form('quran_roots', 'ar', root, None, root, f'{surah}:{ayah}:{word}')
        v = self.db('ds/data-arabic/vocab_cache.sqlite')
        if v:
            for row in v.execute('SELECT token, vocalized, stem, root, pos_tag, reading_academic, gloss, definition FROM token_cache'):
                token, voc, stem, root, pos, reading, gloss, definition = row
                eid = self.entry('atalk_cache', 'ar', token, reading or '', pos, extra={k: x for k, x in (('vocalized', voc), ('stem', stem), ('root', root)) if x})
                self.sense('atalk_cache', eid, gloss, definition=definition)
        cv = self.db('ds/data-arabic/conversions.sqlite')
        if cv:
            for slug, raw, style, tash, res, created in cv.execute('SELECT slug, raw_text, translit_style, auto_tashkeel, result_json, created_at FROM conversions'):
                self.t['texts'].add(self.t['texts'].n + 1, 'ar', slug, raw or '', None, {'app': 'A-Talk'}, self.src['demo_texts'])
                self.counts['demo_texts'] += 1

    def entry_existing_pivot(self, eid, src):
        sid = self.src[src]
        if (eid, sid) not in self.pivot:
            self.pivot.add((eid, sid))
            self.t['entry_sources'].add(eid, sid, None)
            self.counts[src] += 1

    # ── Conjugations (cooljugator) ─────────────────────────────
    def conjugator(self):
        print('Conjugator')
        c = self.db('ds/all-conjugation-data/conjugator.db')
        if not c:
            return
        verb_entry = {}
        for vid, code, verb, meaning, pron, url, translit in c.execute(
                'SELECT id, lang_code, verb, meaning, pronunciation, source_url, transliteration FROM verbs'):
            lang = LANG_MAP.get(code, code)
            eid = self.entry('cooljugator', lang, verb, translit or '', CONJ_POS.get(code, 'verb'), ext_id=url,
                             extra={'pronunciation': pron} if pron else None)
            verb_entry[vid] = (eid, lang)
            self.sense('cooljugator', eid, meaning)
        cur = c.execute('SELECT verb_id, table_title, tense, pronoun, form, form_trans, transliteration, row_order, col_order FROM conjugations')
        for vid, title, tense, pronoun, form, ftrans, translit, ro, co in cur:
            e = verb_entry.get(vid)
            if not e or not form:
                continue
            self.t['conj_forms'].add(self.t['conj_forms'].n + 1, e[0], self.src['cooljugator'], title or '', tense or '', pronoun or '',
                                     form.strip(), ftrans or None, translit or None, (ro or 0) * 100 + (co or 0))
            self.counts['cooljugator'] += 1
        for vid, target, en in c.execute('SELECT verb_id, sentence_target, sentence_en FROM examples'):
            e = verb_entry.get(vid)
            if not e or not target:
                continue
            self.t['sentences'].add(self.t['sentences'].n + 1, e[1], target, None, en, 'en', e[0], None, self.src['cooljugator'])
            self.counts['cooljugator'] += 1
        for vid, rel, meaning in c.execute('SELECT verb_id, related_verb, related_meaning FROM related_verbs'):
            e = verb_entry.get(vid)
            if not e:
                continue
            other = self.find(e[1], rel) or self.entry('cooljugator', e[1], rel, '', 'verb')
            self.sense('cooljugator', other, meaning)
            self.t['links'].add(self.t['links'].n + 1, e[0], other, 'related', None, None, self.src['cooljugator'])
            self.counts['cooljugator'] += 1

    # ── 19parse polyglot registry ──────────────────────────────
    def polyglot(self):
        print('Polyglot registry')
        c = self.db('ds/translations-data/database.sqlite')
        if not c:
            return
        ids = {}
        for wid, lang, word, nw, cnt, pos, cat, note, translit in c.execute(
                'SELECT id, language_code, word, normalized_word, count, pos, category, note, transliteration FROM words'):
            ids[wid] = self.entry('polyglot_registry', lang, word, translit or '', pos or '', extra={'count': cnt, 'category': cat} if cat else {'count': cnt})
        for a, b, btype, conf, note in c.execute('SELECT source_word_id, target_word_id, bond_type, confidence, registry_note FROM translation_bonds'):
            if ids.get(a) and ids.get(b):
                self.t['links'].add(self.t['links'].n + 1, ids[a], ids[b], 'translation', conf, btype, self.src['polyglot_registry'])
                self.counts['polyglot_registry'] += 1
        for lang, text, translit, tr_en, cat, note, toks in c.execute(
                'SELECT language_code, original_text, transliteration, translation_en, category, note, tokens_json FROM sentences'):
            self.t['sentences'].add(self.t['sentences'].n + 1, lang, text, translit, tr_en, 'en', None, {'category': cat} if cat else None, self.src['polyglot_registry'])
            self.counts['polyglot_registry'] += 1
        for row in c.execute('SELECT char, script, subscript, pinyin, furigana, onyomi, kunyomi, transliteration, meaning, radical, stroke_count, grade_or_hsk FROM character_dictionary'):
            ch, script, sub, py, fu, on, kun, tr, meaning, rad, strokes, grade = row
            readings = {k: v for k, v in (('pinyin', py), ('furigana', fu), ('on', on), ('kun', kun), ('translit', tr)) if v}
            self.t['chars'].add(self.t['chars'].n + 1, ch, sub or script or '', readings, meaning, rad, strokes if isinstance(strokes, int) else None, None,
                                {'grade_or_hsk': grade} if grade else None, None, self.src['polyglot_chars'])
            self.counts['polyglot_chars'] += 1

    # ── C-Talk (articles, audio, concepts) + other clone demo texts ──
    def ctalk(self):
        print('C-Talk / demo texts')
        seen = set()
        for rel in ('pc/19ctalks/ctalk.db', 'talks/15ctalk/ctalk.db'):
            c = self.db(rel)
            if not c:
                continue
            cols = [r[1] for r in c.execute('PRAGMA table_info(articles)')]
            lang_col = 'lang' if 'lang' in cols else "'zh'"
            for row in c.execute(f'SELECT type, hsk_level, category, title_zh, title_pinyin, title_en, date_str, audio_url, overview_zh, overview_en, content_json, {lang_col} FROM articles'):
                typ, hsk, cat, tzh, tpy, ten, date, audio, ovzh, oven, content, lang = row
                key = (tzh, date)
                if key in seen:
                    continue
                seen.add(key)
                tid = self.t['texts'].add(self.t['texts'].n + 1, lang or 'zh', tzh or '', content or '', f'HSK{hsk}' if hsk else None,
                                          {k: v for k, v in (('type', typ), ('category', cat), ('title_pinyin', tpy), ('title_en', ten), ('date', date),
                                                             ('overview_zh', ovzh), ('overview_en', oven)) if v}, self.src['easymandarin'])
                self.counts['easymandarin'] += 1
                if audio:
                    self.t['media'].add(self.t['media'].n + 1, lang or 'zh', 'audio', audio, tid, self.src['easymandarin'])
                    self.counts['easymandarin'] += 1
            for _id, title, content, opt, created in c.execute('SELECT id, title, content, convert_option, created_at FROM shares'):
                self.t['texts'].add(self.t['texts'].n + 1, 'zh', title or '', content or '', None, {'app': 'C-Talk'}, self.src['demo_texts'])
                self.counts['demo_texts'] += 1
        c = self.db('pc/19ctalks/ctalk.db')
        if c:
            concept = {}
            for cid, key, cat, en, pos in c.execute('SELECT id, concept_key, category, en_gloss, pos FROM multilingual_concepts'):
                concept[cid] = self.entry('ctalk_multilingual', 'en', key, '', pos or '', extra={'category': cat})
                self.sense('ctalk_multilingual', concept[cid], en)
            for row in c.execute('SELECT concept_id, lang, word, translit, reading, pos, root_or_radical, definition, sample_sentence, sample_translation FROM multilingual_words'):
                cid, lang, word, translit, reading, pos, root, definition, ss, st = row
                eid = self.entry('ctalk_multilingual', lang, word, reading or translit or '', pos or '', extra={'root': root} if root else None)
                self.sense('ctalk_multilingual', eid, definition)
                if concept.get(cid) and eid:
                    self.t['links'].add(self.t['links'].n + 1, concept[cid], eid, 'concept', None, None, self.src['ctalk_multilingual'])
                if ss:
                    self.t['sentences'].add(self.t['sentences'].n + 1, lang, ss, None, st, 'en', eid, None, self.src['ctalk_multilingual'])
            for a, b, rtype, note in c.execute('SELECT source_concept_id, target_concept_id, relation_type, note FROM multilingual_relations'):
                if concept.get(a) and concept.get(b):
                    self.t['links'].add(self.t['links'].n + 1, concept[a], concept[b], rtype or 'related', None, note, self.src['ctalk_multilingual'])
        j = self.db('ds/data-japanese/dictionary.db')
        if j:
            for _id, slug, title, content in j.execute('SELECT id, slug, title, content FROM conversions'):
                self.t['texts'].add(self.t['texts'].n + 1, 'ja', title or slug or '', content or '', None, {'app': 'J-Talk'}, self.src['demo_texts'])
                self.counts['demo_texts'] += 1

    # ── output ─────────────────────────────────────────────────
    def finish(self):
        with open(self.out / 'entries.tsv', 'w', encoding='utf-8') as f:
            for (lang, hw, reading, pos), (eid, freq, level, extra) in self.entries.items():
                f.write('\t'.join(esc(x) for x in (eid, lang, hw, norm(lang, hw), reading, pos, freq, level, extra)) + '\n')
        with open(self.out / 'sources.tsv', 'w', encoding='utf-8') as f:
            for code, (name, url, lic, lic_url, vis, origin, notes) in SOURCES.items():
                attribution = f'{name} — {lic}' + (f' ({url})' if url else '')
                f.write('\t'.join(esc(x) for x in (self.src[code], code, name, url, lic, lic_url, attribution, vis, origin, notes)) + '\n')
        for t in self.t.values():
            t.close()
        report = {
            'entries': len(self.entries),
            'tables': {n: t.n for n, t in self.t.items()},
            'rows_per_source': self.counts,
            'entries_per_lang': {},
        }
        for (lang, *_rest) in self.entries:
            report['entries_per_lang'][lang] = report['entries_per_lang'].get(lang, 0) + 1
        report['entries_per_lang'] = dict(sorted(report['entries_per_lang'].items(), key=lambda kv: -kv[1]))
        (self.out / 'report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2))
        print(json.dumps({k: report[k] for k in ('entries', 'tables')}, indent=2))


def main(root, out):
    b = Builder(Path(root), Path(out))
    # Order matters a little: dictionaries with good readings first, so
    # later sources (HSK lists, related verbs, arabeyes) attach to them.
    b.chinese()
    b.japanese()
    b.european()
    b.russian()
    b.arabic()
    b.conjugator()
    b.polyglot()
    b.ctalk()
    b.finish()


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
